### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by erioness1125** [CPTeam1/translator#1]
Here's the wireframes:
https://raw.githubusercontent.com/CPTeam1/translator/master/wireframes.jpg

and below is the clickable mockups
https://popapp.in/w/projects/56328e07c44f968229135250/preview/56d665a2d0834bb17887ce5f

/cc @codepathreview @codepath

**Comment by ipande** [comment]
Looks really good :+1:

**Comment by nidhi1608** [comment]
Thanks for submitting this and documenting your progress so far! Good to see you have an initial version of the wireframes complete as a starting point for your app.

Remember that by the end of your second sprint, we expect each team to have their core flows functionally complete (but rough) so this week your team should complete the first 50% of your core functionality.

While building this app, try to keep in your mind the story for your app and what you need to have a polished demo. Be aggressive about which features you can scope into the first version for internal demo day. Excited to see what your group comes up with! Let us know what we can do to help.
