### ISSUE TITLE
Error in fetching ParseObject<Entry> from backend!

### ISSUE THREAD

**Issue by elanelango** [CPTeam1/translator#35]
When I ask a question, the post gets added back to the main recyler view. When I click on the newly added question item, I get:

03-20 14:34:51.830 21561-21561/com.cp1.translator E/socialtranslator: in PostActivity: Error in fetching ParseObject<Entry> from backend!

**Comment by ipande** [comment]
I think this has been fixed by Hyunji.. @erioness1125 Could you comment?

**Comment by erioness1125** [comment]
I believe I have fixed this bug when I finished the issue #34.
Elan, please check if this issue has been resolved when you test it again :)
