### ISSUE TITLE
Can't post question with photo. Photo fills the screen.

### ISSUE THREAD

**Issue by elanelango** [CPTeam1/translator#37]
I'm testing on my nexus 5 phone.
In question/answer dialog, when I take a photo, the photo fills the entire dialog and I'm not able to type any text or click on the submit button.

![image_bug](https://cloud.githubusercontent.com/assets/650685/13908581/a817ff48-eec2-11e5-85f2-07e7b53e349e.png)

**Comment by ipande** [comment]
This has been fixed by e04dd5515ab97cf5070b70b31e40b9b107279450
